# No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
# The build has been terminated

language: node_js

node_js:
  - "0.12"

before_script:
  # - npm install -g bower
  - npm install -g bower karma grunt-cli jshint
  - npm install
  - bower install
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # - npm start > /dev/null &
  # - webdriver-manager update
  # - travis_wait
  # - sleep 3
  # - "npm install -g npm@1.4.28"
  # - "npm install -g npm@latest"

# before_install:
#   - npm install -g npm@'>=2.9.1'

  # - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  # - "npm config set spin false"
  # - "npm install -g npm@^2"

# sudo: false

# cache:
#   directories:
#     - node_modules

script:
  - npm test --single-run
  # - node_modules/.bin/protractor e2e/conf.js --browser=firefox
  # - node_modules/.bin/protractor e2e/conf.js --browser=google
  # - '[ "${TRAVIS_NODE_VERSION}" = "0.12" ] && travis_retry travis_wait make browser-test || true'
