language: node_js

node_js:
  - "0.12"

before_script:
  - npm install
  - bower install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm start > /dev/null &
  - webdriver-manager update
  - travis_wait

script:
  - npm test --single-run
