language: node_js

node_js:
  - "0.12"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install -g bower
  - npm install
  - bower install

before_script:
  - npm start > /dev/null &
  - webdriver-manager update
  - sleep 3

script:
  - npm test
  - node_modules/.bin/protractor test/e2e/conf.js --browser=chrome
